CONTACT_FIELDS = {
    "preferred_call_time": "STRING",
    "quiz_complete_date": "STRING",
    "q6": "STRING",
    "q5": "STRING",
    "q4_other": "STRING",
    "q4": "STRING",
    "q3": "STRING",
    "q2_explained": "STRING",
    "q2": "STRING",
    "q1_explained": "STRING",
    "q1": "STRING",
    "preferred_response_time": "STRING",
    "response_time_satisfaction": "STRING",
    "topic_expectations": "STRING",
    "expectation": "STRING",
    "close_case": "TIMESTAMP",
    "open_case": "TIMESTAMP",
    "question_count": "INTEGER",
    "main_menu_count": "INTEGER",
    "first_choice": "STRING",
    "last_call_duration": "STRING",
    "uncaught_message": "STRING",
    "error_count": "INTEGER",
    "love_option": "STRING",
    "first_interaction": "TIMESTAMP",
    "urnsmerge": "STRING",
    "handover_timestamp": "TIMESTAMP",
    "gender": "STRING",
    "county": "STRING",
    "counsellor_request": "STRING",
    "urn": "STRING",
    "age": "STRING",
    "uuid": "STRING",
    "name": "STRING",
    "modified_on": "TIMESTAMP",
}

GROUP_CONTACT_FIELDS = {"group_uuid": "STRING", "contact_uuid": "STRING"}
GROUP_FIELDS = {"name": "STRING", "uuid": "STRING"}
FLOWS_FIELDS = {"labels": "STRING", "name": "STRING", "uuid": "STRING"}
FLOW_RUNS_FIELDS = {
    "modified_on": "TIMESTAMP",
    "responded": "BOOLEAN",
    "contact_uuid": "STRING",
    "flow_uuid": "STRING",
    "exit_type": "STRING",
    "created_at": "TIMESTAMP",
    "exited_on": "TIMESTAMP",
    "id": "INTEGER",
}
PAGEVIEW_FIELDS = {
    "timestamp": "TIMESTAMP",
    "page": "INTEGER",
    "revision": "INTEGER",
    "id": "INTEGER",
}
FLOW_RUN_VALUES_FIELDS = {
    "input": "STRING",
    "time": "TIMESTAMP",
    "category": "STRING",
    "name": "STRING",
    "value": "STRING",
    "run_id": "INTEGER",
}
